// lib/web3/config.ts

export const CONTRACTS = {
  AGENT_FACTORY: process.env.NEXT_PUBLIC_AGENT_FACTORY_ADDRESS!,
  ARENA: process.env.NEXT_PUBLIC_ARENA_ADDRESS!,
  ITEM_FACTORY: process.env.NEXT_PUBLIC_ITEM_FACTORY_ADDRESS!,
};
